CREATE TABLE pictures
(
    id           BIGINT       NOT NULL,
    name_picture VARCHAR(255) NOT NULL,
    created_at   DATE         NOT NULL,
    updated_at   DATE
--     user_favor_id    bigint                 NOT NULL,
--     user_material_id bigint                 NOT NULL
);

ALTER TABLE pictures ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME pictures_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE pictures
    ADD CONSTRAINT pictures_pkey PRIMARY KEY (id);
--
-- ALTER TABLE pictures
--     ADD CONSTRAINT fk_picture_for_favor
--         FOREIGN KEY (user_favor_id) REFERENCES user_favour (id);
--
-- ALTER TABLE pictures
--     ADD CONSTRAINT fk_picture_for_material
--         FOREIGN KEY (user_material_id) REFERENCES user_materials(id);
--
-- ALTER TABLE pictures
--     ADD CONSTRAINT upDel_picture_favor
--         FOREIGN KEY (user_favor_id)
--             REFERENCES favour (id)
--             ON UPDATE CASCADE
--             ON DELETE RESTRICT;
--
-- ALTER TABLE pictures
--     ADD CONSTRAINT upDel_material_favor
--         FOREIGN KEY (user_material_id)
--             REFERENCES materials (id)
--             ON UPDATE CASCADE
--             ON DELETE RESTRICT;