CREATE TABLE rentals
(
    id               BIGINT NOT NULL,
    amount           NUMERIC(7, 2),
    start_date_at    DATE,
    start_time       TIME(6) without time zone,
    end_date_at      DATE,
    end_time         TIME(6) without time zone,
    created_at       DATE   NOT NULL,
    updated_at       DATE,
    bill_id          BIGINT,
    user_favor_id    BIGINT,
    user_id          BIGINT,
    user_material_id BIGINT
);

ALTER TABLE rentals
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME rentals_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE rentals
    ADD CONSTRAINT rentals_pkey PRIMARY KEY (id);

ALTER TABLE rentals
    ADD CONSTRAINT fk_rental_to_user_favor
        FOREIGN KEY (user_favor_id) REFERENCES user_favour (id);

ALTER TABLE rentals
    ADD CONSTRAINT fk_rental_to_user_material
        FOREIGN KEY (user_material_id) REFERENCES user_materials (id);

ALTER TABLE rentals
    ADD CONSTRAINT fk_rental_to_bill
        FOREIGN KEY (bill_id) REFERENCES bills (id);

ALTER TABLE rentals
    ADD CONSTRAINT fk_rentals_from_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE rentals
    ADD CONSTRAINT upDel_rental_user
        FOREIGN KEY (bill_id)
            REFERENCES bills (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;