CREATE TABLE picture_user_materials
(
    id               BIGINT PRIMARY KEY NOT NULL,
    picture_id       BIGINT             NOT NULL,
    user_material_id BIGINT             NOT NULL,
    CONSTRAINT fk_picture_material UNIQUE (picture_id, user_material_id),
    CONSTRAINT fk_pic_picture FOREIGN KEY (picture_id) REFERENCES pictures (id) ON DELETE CASCADE,
    CONSTRAINT fk_pict_user_material FOREIGN KEY (user_material_id) REFERENCES user_materials (id) ON DELETE CASCADE
);

ALTER TABLE picture_user_materials
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME picture_usermaterial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);