CREATE TABLE users
(
    id         BIGINT       NOT NULL,
    first_name VARCHAR(150) NOT NULL,
    name       VARCHAR(200) NOT NULL,
    birthdate  DATE         NOT NULL,
    pseudo     VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(255) NOT NULL,
    street     VARCHAR(255) NOT NULL,
    city       VARCHAR(100) NOT NULL,
    zip_code   VARCHAR(60)  NOT NULL,
    is_active  BOOLEAN      NOT NULL,
    created_at DATE         NOT NULL,
    updated_at DATE,
    CONSTRAINT users_role_check CHECK (
        ((role)::text = ANY ((ARRAY['MEMBER':: VARCHAR, 'MODERATOR':: VARCHAR, 'ADMIN':: VARCHAR])::text[])
)
    )
);

ALTER TABLE users
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT users_pseudo_key UNIQUE (pseudo);