CREATE TABLE users
(
    id         bigint                 NOT NULL,
    first_name character varying(150) NOT NULL,
    name       character varying(200) NOT NULL,
    birthdate  DATE                   NOT NULL,
    pseudo     character varying(255) NOT NULL,
    email      character varying(255) NOT NULL,
    password   character varying(255) NOT NULL,
    role       character varying(255) NOT NULL,
    street     character varying(255) NOT NULL,
    city       character varying(100) NOT NULL,
    zip_code   character varying(60)  NOT NULL,
    is_active  boolean                NOT NULL,
    created_at DATE                   NOT NULL,
    updated_at DATE,
    CONSTRAINT users_role_check CHECK (
        ((role)::text = ANY ((ARRAY['MEMBER':: character varying, 'MODERATOR':: character varying, 'ADMIN':: character varying])::text[])
)
    )
);

ALTER TABLE users
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT users_pseudo_key UNIQUE (pseudo);