CREATE TABLE second_residences
(
    id         bigint                 NOT NULL,
    created_at DATE                   NOT NULL,
    updated_at DATE,
    street     character varying(255) NOT NULL,
    city       character varying(100) NOT NULL,
    zip_code   character varying(50)  NOT NULL,
    user_id    bigint                 NOT NULL
);

ALTER TABLE second_residences
ALTER
COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
      SEQUENCE NAME second_residences_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1
      );

ALTER TABLE second_residences
    ADD CONSTRAINT second_residences_pkey PRIMARY KEY (id);

ALTER TABLE second_residences
    ADD CONSTRAINT fk_second_residences_to_user
        FOREIGN KEY (user_id)
            REFERENCES users (id);

ALTER TABLE second_residences
    ADD CONSTRAINT upDel_second_residences
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;