CREATE TABLE categories
(
    id            bigint                 NOT NULL,
    name_category character varying(150) NOT NULL,
    created_at    DATE                   NOT NULL,
    updated_at    DATE
);

ALTER TABLE categories
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME categories_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE categories
    ADD CONSTRAINT categories_name_category_key UNIQUE (name_category);

ALTER TABLE ONLY categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);