CREATE TABLE user_materials
(
    id                   BIGINT        NOT NULL,
    description_material TEXT,
    price_hour_material  NUMERIC(7, 2) NOT NULL,
    state_material       VARCHAR(255),
    is_available         BOOLEAN,
    created_at           DATE          NOT NULL,
    updated_at           DATE,
    material_id          BIGINT        NOT NULL,
    user_id              BIGINT        NOT NULL,
    CONSTRAINT materials_state_material_check CHECK (((state_material)::text = ANY ((ARRAY['GOOD_STATE':: character varying, 'BAD_STATE':: character varying, 'DAMAGED_STATE':: character varying])::text[])
) )
);

ALTER TABLE user_materials
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME user_materials_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE user_materials
    ADD CONSTRAINT user_materials_pkey PRIMARY KEY (id);


ALTER TABLE user_materials
    ADD CONSTRAINT fk_user_material_to_material
        FOREIGN KEY (material_id) REFERENCES materials (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;

ALTER TABLE user_materials
    ADD CONSTRAINT fk_user_material_from_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;