CREATE TABLE user_favour
(
    id                BIGINT        NOT NULL,
    description_favor TEXT,
    price_hour_favor  numeric(7, 2) NOT NULL,
    is_available      BOOLEAN,
    created_at        DATE          NOT NULL,
    updated_at        DATE,
    favor_id          BIGINT        NOT NULL,
    user_id           BIGINT        NOT NULL
);

ALTER TABLE user_favour
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME user_favour_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE user_favour
    ADD CONSTRAINT user_favour_pkey PRIMARY KEY (id);

ALTER TABLE user_favour
    ADD CONSTRAINT fkuser_favour_from_user
        FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_favour
    ADD CONSTRAINT fk_user_favour_to_favor
        FOREIGN KEY (favor_id) REFERENCES favour (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;

ALTER TABLE user_favour
    ADD CONSTRAINT fk_user_favour_from_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;