CREATE TABLE bills
(
    id         bigint        NOT NULL,
    amount     numeric(7, 2) NOT NULL,
    status     character varying(255),
    created_at DATE          NOT NULL,
    updated_at DATE,
    user_id    bigint,
    is_paid    boolean,
    CONSTRAINT bills_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING':: character varying, 'IN_PROGRESS':: character varying, 'PAID':: character varying, 'CANCELLED':: character varying, 'OVERDUE':: character varying, 'FAILED':: character varying])::text[])
) )
);

ALTER TABLE bills
ALTER
COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME bills_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE bills
    ADD CONSTRAINT bills_pkey PRIMARY KEY (id);

ALTER TABLE bills
    ADD CONSTRAINT fk_bills_to_user
        FOREIGN KEY (user_id) REFERENCES users (id);