CREATE TABLE reviews
(
    id               BIGINT NOT NULL,
    rating           DOUBLE PRECISION,
    comment          TEXT,
    created_at       DATE   NOT NULL,
    updated_at       DATE,
    user_favor_id    BIGINT,
    user_material_id BIGINT,
    is_active        BOOLEAN
);

ALTER TABLE reviews ALTER COLUMN id
    ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME reviews_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_to_user_materials
        FOREIGN KEY (user_material_id) REFERENCES user_materials (id);

ALTER TABLE reviews
    ADD CONSTRAINT fk_review_comment_favor FOREIGN KEY (user_favor_id) REFERENCES user_favour (id);